# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1

jobs:
  docs-test:
    docker:
      - image: python:3.9
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
#      - run:
#          name: Install tool for using Markdown
#          command: pip install myst-parser
      - run:
          name: What is here?
          command: |
            echo $PWD
            ls -aslh .
      - run:
          name: Build base docs
          command: sphinx-build -b html -W amperity_base/source ./site-test/
      - run:
          name: Build AmpIQ user guides
          command: sphinx-build -b html -W amperity_ampiq/source ./site-test/ampiq
      - run:
          name: Build Amp360 user guides
          command: sphinx-build -b html -W amperity_amp360/source ./site-test/amp360
      - run:
          name: Build Operators guide
          command: sphinx-build -b html -W amperity_datagrid/source ./site-test/datagrid
      - run:
          name: Build API
          command: sphinx-build -b html -W amperity_api/source ./site-test/api
      - run:
          name: Build A-Z reference
          command: sphinx-build -b html -W amperity_reference/source ./site-test/reference
      - run:
          name: Build Contributing
          command: sphinx-build -b html -W contributing/source ./site-test/contributing

      - run:
          name: Test deleting files
          command: |
            echo $PWD
            ls -aslh .
            cd site-test
            ls -aslh .
            cd contributing
            ls -aslh .
            rm -r _sources/*
            rm -r .doctrees/*
            rm .buildinfo
            rm genindex.html
            rm objects.inv
            rm searchindex.js
            ls -aslh .
            cd ..
            ls -aslh .



  docs-deploy:
    docker:
      - image: cimg/base:2021.11
    resource_class: small
    steps:
      - run:
          name: ping docs build pipeline
          command: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/amperity/docs/pipeline \
            --header 'Circle-Token: $AMPERITY_DOCS' \
            --header 'content-type: application/json' \
            --data '{"parameters":{"amperity-docs-deploy":true}}'



workflows:
  version: 2
  build:
    jobs:
      - docs-test
      - docs-deploy:
#        requires:
#            - docs-test
          filters:
            branches:
              only: main
