# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1

jobs:
  docs-test:
    docker:
      - image: python:3.7
    resource_class: medium
    steps:
#      - run:
#          name: Placeholder ECHO $PWD
#          command: |
#            echo $PWD
      - checkout
#      - run:
#          name: Post-checkout WTF is here
#          command: |
#            echo $PWD
#            ls -aslh .
#      - add_ssh_keys:
#          fingerprints:
#            - "SHA256:RgCpYZUJ4BY0EKSVzT9rCyOoEgWTeKyDL7Su7DYWvEU"
#      - run:
#          name: Download amperity-docs
#          command: git clone https://github.com/amperity/amperity-docs.git
#      - run:
#          name: Post-amperity-docs checkout WTF is here
#          command: |
#            echo $PWD
#            ls -aslh .
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
#      - run:
#          name: Install tool for using Markdown
#          command: pip install myst-parser
      - run:
          name: Post-dependencies WTF is here
          command: |
            echo $PWD
            ls -aslh .
      - run:
          name: Build Contributing
          command: sphinx-build -b html -W contributing/source /output/contributing


  docs-deploy:
    docker:
      - image: cimg/base:2021.11
    resource_class: small
    steps:
      - run:
          name: ping docs build pipeline
          command: |
            curl -u CCIPRJ_2zpnd68oVAr8HZfUSVGwJf_148c04e74bc59b03acfc89c49e669ec402eabbe0:
                 -d build_parameters[docs-deploy]=deploy_docker
                 https://circleci.com/api/v1.1/project/vcs-type/amperity/docs/tree/master


# curl -u $CCIPRJ_XccNCdTVC3XbxYVgFhFdDU_1f19ba884c6ff0ae5ad0776611cfadb170dab282: -X POST --header "Content-Type: application/json" -d '{
#                             "branch": "feat",
#                             "parameters": {
#                                "workflow_ondemand": true,
#                                "workflow_job2_ondemand": true,
#                                "workflow_job2_param1_version": "version1"
#                              }
# }' https://circleci.com/api/v2/project/gh/amperity/docs/pipeline





workflows:
  version: 2
  build:
    jobs:
      - docs-test
      - docs-deploy:
#          requires:
#            - docs-test
          filters:
            branches:
              only: main
