# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1

jobs:
  docs-test:
    docker:
      - image: python:3.9
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
#      - run:
#          name: Install tool for using Markdown
#          command: pip install myst-parser
      - run:
          name: Post-dependencies WTF is here
          command: |
            echo $PWD
            ls -aslh .
      - run:
          name: Build Contributing
          command: sphinx-build -b html -W contributing/source /output/contributing


  docs-deploy:
    docker:
      - image: cimg/base:2021.11
    resource_class: small
    steps:
      - run:
          name: ping docs build pipeline
          command: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/amperity/docs/pipeline \
            --header 'Circle-Token: CCIPAT_PxhepZeHxpa3uNGM33sDib_c8d4e85dbe3e2885817e42d0840095efc5bb1891' \
            --header 'content-type: application/json' \
            --data '{"parameters":{"amperity-docs-deploy":true}}'



workflows:
  version: 2
  build:
    jobs:
      - docs-test
      - docs-deploy:
#        requires:
#            - docs-test
          filters:
            branches:
              only: main
